name: finans_takipp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"  # Flutter için uyumlu SDK sürümünü belirttik

dependencies:
  flutter:
    sdk: flutter  # Buradaki hatayı düzelttik
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.2
  animated_bottom_navigation_bar: ^1.4.0
  intl: ^0.20.2
  stateless: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
